-- +goose Up
DROP PROCEDURE IF EXISTS hpg_00101_up;
DELIMITER $$
CREATE PROCEDURE hpg_00101_up()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='api_keys' AND COLUMN_NAME='use_count') THEN
        ALTER TABLE api_keys ADD COLUMN use_count BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER last_used_ip;
    END IF;
END $$
DELIMITER ;
CALL hpg_00101_up();
DROP PROCEDURE IF EXISTS hpg_00101_up;

-- +goose Down
DROP PROCEDURE IF EXISTS hpg_00101_down;
DELIMITER $$
CREATE PROCEDURE hpg_00101_down()
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='api_keys' AND COLUMN_NAME='use_count') THEN
        ALTER TABLE api_keys DROP COLUMN use_count;
    END IF;
END $$
DELIMITER ;
CALL hpg_00101_down();
DROP PROCEDURE IF EXISTS hpg_00101_down;
