package security

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"strconv"
)

// MTLSRBACHeaderToken is the header carrying the panel-issued check token, and
// MTLSRBACHeaderNode the node id it was issued to. Both are written by the
// panel into the node's Caddy config, so only a node actually serving the route
// can present them.
const (
	MTLSRBACHeaderToken = "X-Hpg-Rbac-Token"
	MTLSRBACHeaderNode  = "X-Hpg-Node"
)

// MTLSRBACKeyLabel is the HKDF label for the RBAC-check MAC key.
const MTLSRBACKeyLabel = "mtls-rbac"

// MTLSRBACToken derives the check token for one (node, route) pair.
//
// The /internal/mtls-rbac endpoint trusts the X-Mtls-Subject header its caller
// sets, and its only other gate is an IP allow-list spanning the whole WG mesh
// plus the configured trusted proxies. This token narrows that trust: it is
// generated by the control plane into exactly one node's Caddy config, so only
// a node the panel placed the route on can run role checks for that route
// (MTLS-01). It is a MAC over stable identifiers, so it needs no storage and
// stops being valid the moment the route leaves the node (the panel re-checks
// placement server-side).
func MTLSRBACToken(key []byte, nodeID, routeID int64) string {
	if len(key) == 0 || nodeID <= 0 || routeID <= 0 {
		return ""
	}
	mac := hmac.New(sha256.New, key)
	// Length-free but unambiguous: ids are digits, separators are not.
	mac.Write([]byte("mtls-rbac:v1:node="))
	mac.Write([]byte(strconv.FormatInt(nodeID, 10)))
	mac.Write([]byte(":route="))
	mac.Write([]byte(strconv.FormatInt(routeID, 10)))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
}

// VerifyMTLSRBACToken reports whether token is the valid check token for the
// (node, route) pair. Constant-time.
func VerifyMTLSRBACToken(key []byte, nodeID, routeID int64, token string) bool {
	want := MTLSRBACToken(key, nodeID, routeID)
	if want == "" || token == "" {
		return false
	}
	return hmac.Equal([]byte(want), []byte(token))
}
