package wireguard

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

// ConfigWriter renders /config/wg0.conf for the WG sidecar.
// Atomic via temp-file + rename. Concurrent writes serialized by mu.
type ConfigWriter struct {
	Dir string // shared volume path, e.g. /app/wg
	mu  sync.Mutex
}

// Render builds the textual config from control-plane state + peers
// (caddy_nodes with wg_public_key + wg_ip populated).
func (cw *ConfigWriter) Render(ctx context.Context, db *sql.DB, cp ControlPlane) (string, error) {
	if cp.PrivateKey == "" || cp.PublicKey == "" {
		return "", errors.New("wg keypair not generated yet — save WireGuard settings first")
	}
	if cp.ListenPort == 0 {
		cp.ListenPort = 51820
	}
	if cp.ControlIP == "" || cp.Subnet == "" {
		return "", errors.New("wireguard.control_ip / subnet not configured")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Hostyt Proxy Gateway — %s\n", time.Now().UTC().Format(time.RFC3339))
	b.WriteString("# Do NOT edit by hand. The control plane re-renders this file\n")
	b.WriteString("# every time a node joins, leaves, or changes.\n\n")
	b.WriteString("[Interface]\n")
	fmt.Fprintf(&b, "Address    = %s/%s\n", cp.ControlIP, prefixLen(cp.Subnet))
	fmt.Fprintf(&b, "ListenPort = %d\n", cp.ListenPort)
	fmt.Fprintf(&b, "PrivateKey = %s\n", cp.PrivateKey)
	b.WriteString("\n")

	// Only approved + enabled nodes join the mesh - unapproved nodes must not
	// be added as peers just because they generated a keypair at join time.
	rows, err := db.QueryContext(ctx,
		`SELECT id, name, wg_public_key, wg_ip
		 FROM caddy_nodes
		 WHERE wg_public_key IS NOT NULL AND wg_public_key <> '' AND wg_ip IS NOT NULL
		   AND approved_at IS NOT NULL AND is_enabled = 1
		 ORDER BY id ASC`)
	if err != nil {
		return "", fmt.Errorf("list peers: %w", err)
	}
	defer rows.Close()
	type peer struct {
		id     int64
		name   string
		pubKey string
		wgIP   string
	}
	var peers []peer
	for rows.Next() {
		var p peer
		var pk, ip sql.NullString
		if err := rows.Scan(&p.id, &p.name, &pk, &ip); err != nil {
			return "", err
		}
		if pk.Valid && ip.Valid {
			p.pubKey, p.wgIP = pk.String, ip.String
			peers = append(peers, p)
		}
	}
	sort.Slice(peers, func(i, j int) bool { return peers[i].id < peers[j].id })

	for _, p := range peers {
		fmt.Fprintf(&b, "# Node #%d (%s)\n", p.id, p.name)
		b.WriteString("[Peer]\n")
		fmt.Fprintf(&b, "PublicKey  = %s\n", p.pubKey)
		fmt.Fprintf(&b, "AllowedIPs = %s/32\n", p.wgIP)
		b.WriteString("PersistentKeepalive = 25\n\n")
	}
	return b.String(), nil
}

// Write renders + atomically writes wg0.conf to Dir.
func (cw *ConfigWriter) Write(ctx context.Context, db *sql.DB, cp ControlPlane) error {
	cw.mu.Lock()
	defer cw.mu.Unlock()
	content, err := cw.Render(ctx, db, cp)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(cw.Dir, 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", cw.Dir, err)
	}
	target := filepath.Join(cw.Dir, "wg0.conf")
	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write tmp: %w", err)
	}
	if err := os.Rename(tmp, target); err != nil {
		return fmt.Errorf("rename: %w", err)
	}
	return nil
}

// prefixLen extracts "24" from "10.66.0.0/24".
func prefixLen(cidr string) string {
	if i := strings.IndexByte(cidr, '/'); i >= 0 && i+1 < len(cidr) {
		return cidr[i+1:]
	}
	return "24"
}
